apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.acme.id }}
spec:
  acme:
    email: {{ .Values.acme.email }}
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: {{ .Values.acme.id }}
    solvers:
    - dns01: {{- .Values.acme.dns01 | nindent 6 }}
