apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-site.fullname" . }}-backend
  labels: {{ include "plugin-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plugin-site.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        # subpath secrets don't get updates, and we want to restart on change anyways
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels: {{ include "plugin-site.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "plugin-site.fullname" . }}
                  key: github_app_id
            - name: GITHUB_APP_PRIVATE_KEY
              value: /secrets/github_app_key
            - name: JIRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "plugin-site.fullname" . }}
                  key: jira_username
            - name: JIRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "plugin-site.fullname" . }}
                  key: jira_password
 {{- if .Values.sentry.dsn }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "plugin-site.fullname" . }}
                  key: sentry_dsn
 {{- end }}
            - name: DATA_FILE_URL
              value: {{ .Values.dataFileUrl }}
          volumeMounts:
            - mountPath: /secrets/github_app_key
              name: secrets
              subPath: github_app_key
          ports:
              - name: backend
                containerPort: {{ .Values.backend.port }}
                protocol: TCP
          livenessProbe:
              httpGet:
                  path: /labels
                  port: {{ .Values.backend.port }}
                  scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              httpGet:
                  path: /labels
                  port: {{ .Values.backend.port }}
                  scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ include "plugin-site.fullname" . }}
