apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-site.fullname" . }}-frontend
  labels: {{ include "plugin-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plugin-site.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels: {{ include "plugin-site.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          {{ if .Values.frontend.image.oldMode -}}
          workingDir: /plugins
          command: ["yarn"]
          args: ["server"]
          {{ end -}}
          ports:
              - name: frontend
                containerPort: {{ .Values.frontend.port }}
                protocol: TCP
          env:
            - name: REST_API_URL
              value: {{ .Values.restApiUrl }}
          {{ if not .Values.frontend.image.oldMode -}}
          livenessProbe:
              httpGet:
                  path: /
                  port: {{ .Values.frontend.port }}
                  scheme: HTTP
              initialDelaySeconds: 5
              timeoutSeconds: 5
          readinessProbe:
              httpGet:
                  path: /
                  port: {{ .Values.frontend.port }}
                  scheme: HTTP
              initialDelaySeconds: 5
              timeoutSeconds: 5
          {{ end -}}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

