  
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkinsio.fullname" . }}-zh
  labels: {{ include "jenkinsio.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
  
    {{- if .Values.forceJenkinsIoHost -}}
      if ( $host != 'www.jenkins.io') {
        return 301 $scheme://www.jenkins.io/zh/$request_uri;
      }
    {{- end }}
  
      root   /usr/share/nginx/html;

      location / {
          index  index.html index.htm;
      }

      location ~* \.(?:css|js|woff|eot|svg|ttf|otf|png|gif|jpe?g) {
        expires 2d;
        add_header Cache-Control "public";
      }

      location ~* \.(html)$ {
        expires 1h;
        add_header Cache-Control "public";
      }
  
      error_page  404              /404/index.html;
  
      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
