dependencies:
  - name: jenkins
    repository: https://charts.jenkins.io
    version: 3.1.11
    import-values:
      - child: jenkins.master
        parent: master
      - child: jenkins.agent
        parent: agent
      - child: jenkins.persistence
        parent: persistence
      - child: jenkins.serviceAccount
        parent: serviceAccount
      - child: jenkins.rbac
        parent: rbac
      - child: jenkins.networkPolicy
        parent: networkPolicy
