---
dependencies:
    - name: jenkins
      repository: https://kubernetes-charts.storage.googleapis.com
      version: 1.7.8
      import-values:
          - child: jenkins.master
            parent: master
          - child: jenkins.agent
            parent: agent
