# Defautl helm value https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml
#
clusterAdminEnabled: false
jenkins:
  rbac:
    create: true
    readSecrets: false
  persistence:
    enabled: true
    size: 50Gi
  master:
    testEnabled: false
    image: jenkins/jenkins
    imageTag: 2.255-jdk11
    ingress:
      apiVersion: networking.k8s.io/v1beta1
    runAsUser: 1000
    fsGroup: 1000
    containerEnv:
      - name: SECRETS
        value: /var/jenkins_secrets
    overwritePlugins: true
    secretsFilesSecret: 'jenkins-secrets'
    serviceType: "ClusterIP"
    installPlugins:
      - ansicolor
      - antisamy-markup-formatter
      - authentication-tokens
      - basic-branch-build-strategies
      - blueocean
      - blueocean-autofavorite
      - blueocean-commons
      - blueocean-config
      - blueocean-core-js
      - blueocean-dashboard
      - blueocean-display-url
      - blueocean-events
      - blueocean-git-pipeline
      - blueocean-github-pipeline
      - blueocean-i18n
      - blueocean-jira
      - blueocean-jwt
      - blueocean-personalization
      - blueocean-pipeline-api-impl
      - blueocean-pipeline-editor
      - blueocean-pipeline-scm-api
      - blueocean-rest
      - blueocean-rest-impl
      - blueocean-web
      - branch-api
      - build-name-setter
      - config-file-provider
      - configuration-as-code
      - credentials
      - credentials-binding
      - extended-read-permission
      - git
      - git-client
      - github
      - github-api
      - github-branch-source
      - github-checks
      - inline-pipeline
      - jira
      - job-dsl
      - junit
      - kubernetes
      - ldap
      - lockable-resources
      - pipeline-utility-steps
      - matrix-auth
      - matrix-project
      - pipeline-build-step
      - pipeline-graph-analysis
      - pipeline-input-step
      - pipeline-milestone-step
      - pipeline-model-api
      - pipeline-model-definition
      - pipeline-model-extensions
      - pipeline-rest-api
      - pipeline-stage-step
      - pipeline-stage-tags-metadata
      - pipeline-stage-view
      - plain-credentials
      - prometheus
      - scm-api
      - script-security
      - ssh-agent
      - ssh-credentials
      - support-core
      - token-macro
      - variant
      - warnings-ng
      - workflow-aggregator
      - workflow-api
      - workflow-basic-steps
      - workflow-cps
      - workflow-cps-global-lib
      - workflow-durable-task-step
      - workflow-job
      - workflow-multibranch
      - workflow-scm-step
      - workflow-step-api
      - workflow-support
      - javadoc
      - metrics
  serviceAccount:
    create: true
    name: jenkins-master
  serviceAccountAgent:
    create: true
    name: jenkins-agent
  networkPolicy:
    enabled: true
