# Default helm value https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
clusterAdminEnabled: false
jenkins:
  rbac:
    create: true
    readSecrets: true
  persistence:
    enabled: true
    size: 50Gi
    volumes:
      - name: jenkins-secrets
        secret:
          secretName: jenkins-secrets
    mounts:
      - name: jenkins-secrets
        mountPath: /var/jenkins_secrets
        readOnly: true
  controller:
    probes:
      startupProbe:
        initialDelaySeconds: 120
      livenessProbe:
        initialDelaySeconds: 120
      readinessProbe:
        initialDelaySeconds: 120
    testEnabled: false
    image: jenkinsciinfra/jenkins-weekly
    tag: 0.5.5-2.293
    ingress:
      apiVersion: networking.k8s.io/v1beta1
    runAsUser: 1000
    fsGroup: 1000
    containerEnv:
      - name: SECRETS
        value: /var/jenkins_secrets
    overwritePlugins: true
    secretsFilesSecret: 'jenkins-secrets'
    serviceType: "ClusterIP"
  serviceAccount:
    create: true
    name: jenkins-controller
  serviceAccountAgent:
    create: true
    name: jenkins-agent
  networkPolicy:
    enabled: true
