nexus:
    secret:
        data:
            ldap_password: ENC[AES256_GCM,data:Z2WXksGfjKG03zTH,iv:fGqRJnN65ef2+7gtuxRxmneDOnI8z6tzBNO73jb8PPA=,tag:CaGJ3zZk3/ZHnmJlFAntYQ==,type:str]
            admin_password: ENC[AES256_GCM,data:3x5bpyalCXbaiNYCFvEDj5Pla8FGgcoSRtG2pQ==,iv:2K+YqqARdCaxurr35CZWYkpr28c2Mzi3Zq6KCXAocDI=,tag:HKtWuFzgw+lujDArlIp0RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://prodjenkinsinfra.vault.azure.net
        name: sops
        version: 252fc7e646ac40f184ab4a6016484725
        created_at: '2019-06-14T12:58:35Z'
        enc: g7YLmMMeWfNQD_9dYPkpaoMwSzbjsQ-Zne1rL_59F9ZuzduPtf08t-EdtP3tdKe5ttc1EDfs77EzhA5CFrwb_MlXj-OCR-c2UViKND0uT4n5vsIOJZUcixZ62if75Sj3-KBJtfr776C80-eFvDKf7JQeaiEARvRoMFfktJ_4IwZerWjtE0wvmP3jsG3ijgBho7rJFdZ9JMUOdm1VJPd8aeay6HTibz_GQaSzoVpSr-6Q37qMbWm1u7lxxWvsfSgu6q0WqLMuVTaA-IUfMAD4ARYg7J8og6jlSC9DKHi8IK49qBX_a2SzItx5R88SgRVoRN3Tol7Cn1puo2DeKskO6_CP6MjR9PYvHtznza7TXUlwFMc47VG_9ORGBqfOybW1OmIlu62w4-G2G-4p3dhMmqQbGy7JfR0-j2NtEE1FOc-0mSrOB-4FdElL9RXSZT4jVT2S0rSHeeCxDp2w0d8nyt3gTLG_gNB5fZ_6FJssA6qX6HES_NnjHAyJAS4kuCegxEpyWZkE24Z1sF-b_nv39NR14c0oRA7YMhKa0LrvN_2yVaZ7Egpxi5LDGAQRnnoPcMvLPcV-FIcqRHF3ZisvazkJRM0lAP30xyq9bpaM1r1vpX_mb2Xc0jkhPJ-d86b7J6uEO71t2m8lOUWrbx7pOdImId8uGyA5UpjvQX253_M
    lastmodified: '2019-06-14T12:58:36Z'
    mac: ENC[AES256_GCM,data:NoC440FBcn2IKz+jsh2YL3Am121H9SpK+O9C+VzxISvKUSg6riynGC5guVCOkCvsDev/po8ppM+lhO+z5dvNiIHlTXu92tQFQGch/7H5WLH40aTWufZbH53TRmwiLq2x5lQAs0oyf3jk5F3gcFebwK/heA7D6Ab9EOS/q2wsaQI=,iv:gN9mJTotdIMzo9qb2TkhH5Unhq30CxJ2MqzoYVETzk0=,tag:G6bpZqTXRvKApHBjwogWNA==,type:str]
    pgp:
    -   created_at: '2019-05-31T13:36:42Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6wcUdUnIIlfARAAJtEl9CQBustINFWtvMGB92d509DJy1c8nmq8dUL9fz3Q
            2vrynTWAIBrL6gzMvO9hA6ffhIPeZagTbAdnazQzpEtpU2VtriLUz5BeLN+YQnrB
            WMvWX5OazbpHTUXewDXUVL0JD3xFfze+b6guz47X/GWmt5rFGi7T86HwnWaQyeEv
            9igT4LxjKBCRkDhs7WdG3kurw3STtutJlhydQ7DBYiol3/6Omqfa9lwjZDVCFe3w
            4d3BIDcWjgdHxyEfGoWbR2mDht4nahyVaBojmAgERaROcU6dDw3RHrnPcPGDwqau
            3nO3X2qRZZ4jPSRb3B7Pc8zXccejhXRHBfP1KrKXv5kAkMf7LeoqvukUc3fB3Mk8
            4cTH9nakM5n7xI7woad2sGwVKPJJiHM9IKH0cZF/YXPTEfH+JyMbGziBrkijA311
            8K1h69mIRRt1Gs1QVXH334BTo/AdYikAUdYjJaO8amJimI1m9HMKrSYnQTUCROp9
            OV+kVnp41ZEgqPIu9jqwAexVVei2wg9jhGvTunNDd5LJFmnep54ySREs8iIQ/iBI
            0mKLyNGXxoEyEz39my+AoUQ4E+fiUsoQphw/MGarm4kTJOrGfJ+TeuE2a+yDm+XX
            z6mDogsW5cyJaHK54FxFTNW4aXZC0IylXDVA6mTPs1BuYw16zf1RTRQGgcCQ10TS
            4AHkBDiYkkog8q3u67JMF+oPheELtOCl4Drh9aDg6+JVzcgi4BXlCgXMmqEDNPip
            ENPrNNVMcJwB39sb4KNc8LmuEirEItXgQuSsJjkjCmaicuJDG5gumioQ4ge5FPrh
            nA4A
            =rPGA
            -----END PGP MESSAGE-----
        fp: 56D8342434B84E2D1CCF53D96E9A025D52210D3D
    unencrypted_suffix: _unencrypted
    version: 3.2.0
