apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ldap.fullname" . }}-backup
  labels:
    role: ldap-backup
{{ include "ldap.labels" . | indent 4 }}
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - uid=100
    - gid=100
  azureFile:
    secretName: {{ include "ldap.fullname" . }}
    shareName: ldap
    readOnly: false

