apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatbot.fullname" . }}
  labels: {{ include "chatbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chatbot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels: {{ include "chatbot.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # A shell is required to load $NICK_PASSWORD env variable
          # For a reason that I can't understand, the java command must be defined as an argument otherwise it doesn't take into account the $NICK_PASSWORD parameter
          command: ["/tini","--","/bin/sh","-c"]
          args: ["java -Dircbot.name=jenkins-admin -jar /usr/local/bin/ircbot-2.0-SNAPSHOT.jar $NICK_PASSWORD"]
          env:
            - name: NICK_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: {{ include "chatbot.fullname" . }}
                    key: nick_password
          volumeMounts:
            - name: credentials
              mountPath: /home/ircbot
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "chatbot.fullname" . }}
            items:
              - key: github
                path: .github
                mode: 0644
              - key: jira
                path: .jenkins-ci.org
                mode: 0644
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
