---
dependencies:
  - name: sonatype-nexus
    alias: nexus
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.18.4
    import-values:
      - child: nexus.statefulset
        parent: statefulset
      - child: nexus.nexus
        parent: nexus
      - child: nexus.ingress
        parent: ingress
      - child: nexus.nexusProxy
        parent: nexusProxy
      - child: nexus.persistence
        parent: persistence
      - child: nexus.secret
        parent: secret
      - child: nexus.service
        parent: service
      - child: nexus.deployment
        parent: deployment
