---
title: Bump cert-manager helm chart version
sources:
  chartLastVersion:
    kind: helmChart
    spec:
      url: https://charts.jetstack.io
      name: cert-manager
targets:
  updateChartVersion:
    name: "jetstack/cert-manager Helm Chart"
    kind: file
    spec:
      file: cluster/publick8s.yaml
      matchPattern: 'chart: jetstack\/cert-manager(\r\n|\r|\n)\s+version: .*'
      replacePattern: 'chart: jetstack/cert-manager$1version: {{ source `chartLastVersion` }}'
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
