
title: Bump promtail helm chart version
sources:
  lastChartVersion:
    kind: helmChart
    spec:
      url: https://grafana.github.io/helm-charts
      name: promtail
targets:
  updateChartVersion:
    name: "grafana/promtail Helm Chart"
    kind: file
    spec:
      file: clusters/publick8s.yaml
      matchPattern: 'chart: grafana\/promtail((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: grafana/promtail${1}version: {{ source `lastChartVersion` }}'
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
