title: Bump loki helm chart version
pipelineID: bumplokihelmchartversion
sources:
  chartLastVersion:
    kind: helmChart
    spec:
      url: https://grafana.github.io/helm-charts
      name: loki
# conditions:
#   helmfileRelease:
#     name: "grafana/loki Helm Chart"
#     kind: yaml
#     spec:
#       file: "helmfile.d/loki.yaml"
#       key: "releases[0].name"
#       value: "loki"
#     scm:
#       github:
#         user: "{{ .github.user }}"
#         email: "{{ .github.email }}"
#         owner: "{{ .github.owner }}"
#         repository: "{{ .github.repository }}"
#         token: "{{ requiredEnv .github.token }}"
#         username: "{{ .github.username }}"
#         branch: "{{ .github.branch }}"
targets:
  chartVersion:
    name: "grafana/loki Helm Chart"
    kind: yaml
    spec:
      file: cluster/publick8s.yaml
      matchPattern: 'chart: grafana\/loki(\r\n|\r|\n)\s+version: .*'
      replacePattern: 'chart: grafana/loki$1version: {{ source `chartLastVersion` }}'
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
