name: Bump Security Groups on jenkins-infra AND release

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  getNewJenkinsInfraSecurityGroup:
    kind: file
    name: get new Jenkins Infra Security Group
    spec:
      file: https://raw.githubusercontent.com/jenkins-infra/aws/main/locals.tf
      matchpattern: 'aws_security_group.*\["(.*?):'
    transformers:
      - findsubmatch:
          pattern: 'aws_security_group.*\["(.*?):'
          captureindex: 1
      - addprefix: "ec2_agents_"
  getNewJenkinsReleaseSecurityGroup:
    kind: file
    name: get new Jenkins Release Security Group
    spec:
      file: https://raw.githubusercontent.com/jenkins-infra/aws/main/locals.tf
      matchpattern: 'aws_security_group.*\[".*", "(.*?):'
    transformers:
      - findsubmatch:
          pattern: 'aws_security_group.*\[".*", "(.*?):'
          captureindex: 1
      - addprefix: "ec2_agents_"

targets:
  setJenkinsInfraSecurityGroup:
    name: "Bump infra Security Group"
    kind: file
    sourceid: getNewJenkinsInfraSecurityGroup
    spec:
      file: config/ext_jenkins-infra.yaml
      matchpattern: 'securityGroups: ".*"'
      replacepattern: 'securityGroups: "{{ source `getNewJenkinsInfraSecurityGroup` }}"'
    scmid: default
  setJenkinsReleaseSecurityGroup:
    name: "Bump Release Security Group"
    kind: file
    sourceid: getNewJenkinsReleaseSecurityGroup
    spec:
      file: config/ext_jenkins-release.yaml
      matchpattern: 'securityGroups: ".*"'
      replacepattern: 'securityGroups: "{{ source `getNewJenkinsReleaseSecurityGroup` }}"'
    scmid: default

pullrequests:
  default:
    kind: github
    scmid: default
    title: Bump Security Groups on Jenkins Infra and Release
    spec:
      labels:
        - dependencies
        - security-groups
        - infra.ci.jenkins.io
        - release.ci.jenkins.io
