title: "Bump Jenkins Kubernetes Agents Helm Chart Version"
sources:
  lastChartVersion:
    kind: helmChart
    spec:
      url: https://jenkins-infra.github.io/public-charts
      name: jenkins-kubernetes-agents
targets:
  updateChartVersion:
    name: "Update the chart version for jenkins kubernetes agent"
    kind: file
    spec:
      file: clusters/cik8s.yaml
      matchPattern: 'chart: jenkins-infra\/jenkins-kubernetes-agents((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/jenkins-kubernetes-agents${1}version: {{ source `lastChartVersion` }}'
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
