title: "Bump jenkins-additional Helm Chart Version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmChart
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: jenkins-additional

targets:
  updateChartVersionPublic:
    name: "Update the chart version for jenkins-additional"
    kind: file
    spec:
      file: clusters/prodpublick8s.yaml
      matchPattern: 'chart: jenkins-infra\/jenkins-additional((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/jenkins-additional${1}version: {{ source `lastChartVersion` }}'
    scmID: default
  updateChartVersionPrivate:
    name: "Update the chart version for jenkins-additional"
    kind: file
    spec:
      file: clusters/temp-privatek8s.yaml
      matchPattern: 'chart: jenkins-infra\/jenkins-additional((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: jenkins-infra/jenkins-additional${1}version: {{ source `lastChartVersion` }}'
    scmID: default

pullrequests:
  default:
    kind: github
    scmID: default
    targets:
      - updateChartVersionPublic
      - updateChartVersionPrivate
    spec:
      labels:
        - dependencies
        - jenkins-additional
