name: Bump nginx-ingress helm chart

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    name: "Retrieve latest version of the chart ingress-nginx"
    kind: helmchart
    spec:
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx

targets:
  updateChartVersion:
    name: "Update the version of the Helm chart ingress-nginx"
    kind: yaml
    spec:
      files:
        - clusters/privatek8s.yaml
        - clusters/publick8s.yaml
      engine: yamlpath
      key: $.releases[?(@.chart == 'ingress-nginx/ingress-nginx')].version
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump `nginx-ingress` helm chart version to {{ source "lastChartVersion" }}
    spec:
      labels:
        - dependencies
        - nginx-ingress
