title: Bump nginx-ingress helm chart

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    name: "Retrieve latest version of the chart ingress-nginx"
    kind: helmChart
    spec:
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx

targets:
  updateChartVersionPublic:
    name: "Update the version of the Helm chart ingress-nginx for public-ingress"
    kind: file
    spec:
      file: clusters/prodpublick8s.yaml
      matchPattern: 'chart: ingress-nginx\/ingress-nginx((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: ingress-nginx/ingress-nginx${1}version: {{ source `lastChartVersion` }}'
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
  updateChartVersionPrivate:
    name: "Update the version of the Helm chart ingress-nginx for temp-privatek8s"
    kind: file
    spec:
      file: clusters/temp-privatek8s.yaml
      matchPattern: 'chart: ingress-nginx\/ingress-nginx((\r\n|\r|\n)(\s+))version: .*'
      replacePattern: 'chart: ingress-nginx/ingress-nginx${1}version: {{ source `lastChartVersion` }}'

pullrequests:
  default:
    kind: github
    scmID: default
    targets:
      - updateChartVersion
