# Common values for all nginx-proxies
resources:
  limits:
    cpu: 2
    memory: 256Mi
  requests:
    cpu: 2
    memory: 256Mi

service:
  port: 8080

persistence:
  enabled: true
  size: 50

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001
  fsGroupChangePolicy: "OnRootMismatch"
