# Common values for all nginx-proxies
resources:
  limits:
    cpu: 2
    memory: 4096Mi
  requests:
    cpu: 2
    memory: 4096Mi

persistence:
  enabled: true
  size: 50

ingress:
  enabled: true
  className: public-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
