geoipupdate:
  dryrun: false
  editions: "GeoLite2-ASN GeoLite2-City GeoLite2-Country"
  storage_name: "publick8spvdata"
  storage_fileshare: "geoip-data"
  cron: '30 0 */3 * *' # every 3 days at 00:30AM
  rolloutrestart:
    enable: true
    restarts:
      - namespace: updates-jenkins-io
        deployments:
          - updates-jenkins-io-content-secured-mirrorbits
          - updates-jenkins-io-content-unsecured-mirrorbits
      - namespace: get-jenkins-io
        deployments:
          - get-jenkins-io-mirrorbits
podSecurityContext:
  runAsUser: 65534  # User 'nobody'
  runAsGroup: 65534  # Group 'nogroup'
  runAsNonRoot: true
resources:
  limits:
    cpu: 500m
    memory: 256Mi # minimum 256Mi to avoid OMM kill for `az login`
  requests:
    cpu: 100m
    memory: 256Mi # minimum 256Mi to avoid OMM kill for `az login`
containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
nodeSelector:
  kubernetes.io/arch: arm64
tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"
