nodeSelector:
  kubernetes.io/arch: arm64
  jenkins: ci.jenkins.io
  role: applications

tolerations:
  - key: "ci.jenkins.io/applications"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

resources:
  limits:
    # No CPU limit to avoid throttling
    memory: 4096Mi
  requests:
    cpu: 1.5
    memory: 4096Mi

service:
  type: LoadBalancer
  annotations:
    # Internal LB, with fixed IP in private subnet where EC2 VM agents are running
    # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/
    service.beta.kubernetes.io/aws-load-balancer-type: "internal"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    # We want the LB to directly send requests to the Pod IPs (requires VPC-CNI)
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    # Tracked by updatecli (updatecli/updatecli.d/configs/docker-registry-aws.yaml)
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-003b868ae937f290a"
    # Tracked by updatecli (updatecli/updatecli.d/configs/docker-registry-aws.yaml)
    service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: "10.0.131.247"
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "ipv4"
    # Misc.
    service.beta.kubernetes.io/aws-load-balancer-alpn-policy: "HTTP2Preferred"

proxy:
  enabled: true
  remoteurl: "https://registry-1.docker.io"

persistence:
  enabled: true
  deleteEnabled: true
  size: "250Gi"
  storageClass: ebs-csi-premium-retain-us-east-2a

initContainers:
  - name: permission-fix
    image: "busybox"
    command: ['chown', '-R', '1000:1000', '/var/lib/registry']
    volumeMounts:
      - mountPath: /var/lib/registry
        name: data

extraEnvVars:
  # Ref. https://github.com/distribution/distribution/issues/2367#issuecomment-1874449361
  - name: REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR
    value: dummyvalue
