ingress:
  enabled: true
  className: public-nginx
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
    "nginx.ingress.kubernetes.io/ssl-redirect": "false"
  hosts:
    - host: jenkins.io
      paths:
        - path: /
          serviceName: jenkinsio
        - path: /zh/
          serviceName: jenkinsio-zh
    - host: www.jenkins.io
      paths:
        - path: /
          serviceName: jenkinsio
        - path: /zh/
          serviceName: jenkinsio-zh
    - host: www.origin.jenkins.io
      paths:
        - path: /
          serviceName: jenkinsio
        - path: /zh/
          serviceName: jenkinsio-zh
    - host: jenkins-ci.org
      paths:
        - path: /
          serviceName: jenkinsio
        - path: /zh/
          serviceName: jenkinsio-zh
    - host: www.jenkins-ci.org
      paths:
        - path: /
          serviceName: jenkinsio
        - path: /zh/
          serviceName: jenkinsio-zh
  # www.jenkins.io certificate is managed by Fastly
  tls:
    - secretName: jenkinsio-tls
      hosts:
        - jenkins-ci.org
        - jenkins.io
        - www.jenkins-ci.org
        - www.origin.jenkins.io
replicaCount: 5
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
htmlVolume:
  azureFile:
    secretName: jenkinsio
    shareName: jenkinsio
    readOnly: true
zhHtmlVolume:
  azureFile:
    secretName: jenkinsio
    shareName: zhjenkinsio
    readOnly: true
forceJenkinsIoHost: true
images:
  en:
    repository: nginx
    tag: 1.21.5-alpine
    pullPolicy: IfNotPresent
  zh:
    repository: nginx
    tag: 1.20.2-alpine
    pullPolicy: IfNotPresent
