service:
  type: LoadBalancer
  # Public IPv4 defined as code in https://github.com/jenkins-infra/azure/blob/main/ldap.jenkins.io.tf instead of requesting a random new public IP, useful for DNS setup and changes
  # TODO: automate syncing
  azurePip:
    name: ldap-jenkins-io-ipv4
    resourceGroup: prod-public-ips
  whitelisted_sources:
    - '20.85.71.108/32' # Accept inbound connections from publick8s public outbound IP (1/3 IPv4)
    - '20.22.30.9/32' # Accept inbound connections from publick8s public outbound IP (2/3 IPv4)
    - '20.22.30.74/32' # Accept inbound connections from publick8s public outbound IP (3/3 IPv4)
    - '20.7.192.189/32' # Accept inbound connections from publick8s outbound NAT gateway
    - '10.100.0.0/16' # publick8s Pod CIDR (internal IPs) for internal access
    - '73.71.177.172/32' # 106 accept inbound LDAPS request from spambot
    - '140.211.15.101/32' # 107 accept inbound LDAPS request from accounts.jenkins.io
    - '20.12.27.65/32' # 107 accept inbound LDAPS request from puppet.jenkins.io
    - '104.209.128.236/32' # accept inbound LDAPS from trusted.ci.jenkins.io vnet (public IP for the outbound NAT gateway)
    - '172.176.126.194/32' # accept inbound LDAPS from private.vpn.jenkins.io
    - '104.209.153.13/32' # accept inbound LDAPS from cert.ci.jenkins.io vnet (public IP for the outbound NAT gateway)
    - '20.230.90.10/32' # Accept inbound LDAPS from NAT gateway for ci.jenkins.io - https://github.com/jenkins-infra/azure-net/blob/main/gateways.tf#L63-L73 (1/1 IPv4)
    - '172.177.87.156/32' # Accept inbound LDAPS from NAT gateway for ci.jenkins.io "sponsorship" secondary network - https://github.com/jenkins-infra/azure-net/blob/main/gateways.tf#L75-L92 (1/4 IPv4)
    - '68.154.8.163/32' # Accept inbound LDAPS from NAT gateway for ci.jenkins.io "sponsorship" secondary network - https://github.com/jenkins-infra/azure-net/blob/main/gateways.tf#L75-L92 (2/4 IPv4)
    - '172.200.120.16/32' # Accept inbound LDAPS from NAT gateway for ci.jenkins.io "sponsorship" secondary network - https://github.com/jenkins-infra/azure-net/blob/main/gateways.tf#L75-L92 (3/4 IPv4)
    - '172.200.126.194/32' # Accept inbound LDAPS from NAT gateway for ci.jenkins.io "sponsorship" secondary network - https://github.com/jenkins-infra/azure-net/blob/main/gateways.tf#L75-L92 (4/4 IPv4)
    - '34.211.101.61/32' # Accept inbound connections from Linux Foundation test machine
    - '44.240.22.235/32' # Accept inbound connections from Linux Foundation prod machine
    - '20.22.6.81/32' # Accept inbound connections from privatek8s outbound LB # TODO: find out how to retrieve this IP from terraform
    - '20.65.63.127/32' # Accept inbound connections from privatek8s outbound NAT gateway
    - '18.214.241.149/32' # JFrog Public Nat IP for AWS us-east-1 (https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/)
    - '34.201.191.93/32' # JFrog Public Nat IP for AWS us-east-1 (https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/)
    - '34.233.58.83/32' # JFrog Public Nat IP for AWS us-east-1 (https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/)
    - '54.236.124.56/32' # JFrog Public Nat IP for AWS us-east-1 (https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/)
    - '3.146.166.108/32'
resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector:
  kubernetes.io/arch: amd64

tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"

persistence:
  # Tracked by updatecli
  customDataClaimName: ldap-jenkins-io-data
  # Tracked by updatecli
  customBackupClaimName: ldap-jenkins-io-backup
