service:
  type: LoadBalancer
  whitelisted_sources:
    - '10.0.32.0/19'  # Kubernetes publick8s internal IPs
    - '73.71.177.172/32'  # 106 accept inbound LDAPS request from spambot
    - '140.211.15.101/32'  # 107 accept inbound LDAPS request from accounts.jenkins.io
    - '20.12.27.65/32'  # 107 accept inbound LDAPS request from puppet.jenkins.io
    - '20.10.13.69/32'  # 107 accept inbound LDAPS from (controller.)trusted.ci.jenkins.io
    - '52.71.231.250/32'  # 107 accept inbound LDAPS from (AWS) ci.jenkins.io # TODO: sounds like we can remove this one
    - '104.209.251.202/32'  # accept inbound LDAPS from vpn.jenkins.io
    - '172.176.126.194/32'  # accept inbound LDAPS from private.vpn.jenkins.io
    - '104.210.5.242/32'  # accept inbound LDAPS from cert.ci.jenkins.io
    - '104.208.238.39/32'  # Accept inbound LDAPS from ci.jenkins.io
    - '52.167.253.43/32'  # Accept inbound LDAPS from public.aks.jenkins.io # TODO: delete when migration from prodpublick8s to publick8s is completed, see https://github.com/jenkins-infra/helpdesk/issues/3351
    - '20.75.10.224/29'  # Accept inbound connections from prodpublick8s public outbound IPs # TODO: delete when migration from prodpublick8s to publick8s is completed, see https://github.com/jenkins-infra/helpdesk/issues/3351
    - '34.211.101.61/32'  # Accept inbound connections from Linux Foundation test machine
    - '44.240.22.235/32'  # Accept inbound connections from Linux Foundation prod machine
    - '20.62.24.45/32'  # Accept inbound connections from publick8s public outbound IP
    - '20.96.66.246/32'  # Accept inbound connections from privatek8s # TODO: find out how to retrieve this IP from terraform
    - '18.214.241.149/32'  # JFrog Public Nat IP for AWS us-east-1 (https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/)
    - '34.201.191.93/32'  # JFrog Public Nat IP for AWS us-east-1 (https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/)
    - '34.233.58.83/32'  # JFrog Public Nat IP for AWS us-east-1 (https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/)
    - '54.236.124.56/32'  # JFrog Public Nat IP for AWS us-east-1 (https://jfrog.com/knowledge-base/what-are-artifactory-cloud-nated-ips/)
image:
  slapd:
    # repo & '@sha256' suffix here as we're retrieving a docker digest from updatecli
    repository: jenkinsciinfra/ldap@sha256
    tag: "a1518d683d3098be912a684892d10f909dd6c5bf2a65dce3f477a2caab73ef22"
    pullPolicy: IfNotPresent
  crond:
    # repo & '@sha256' suffix here as we're retrieving a docker digest from updatecli
    repository: jenkinsciinfra/ldap@sha256
    tag: d662790b4a5f1ca979c186241005e816ff86ccedf8161d9f11df43501f077f31
    pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 500m
    memory: 1536Mi
  requests:
    cpu: 500m
    memory: 1536Mi
