service:
  type: LoadBalancer
  # Public IPv4 defined as code in https://github.com/jenkins-infra/azure/blob/main/ldap.jenkins.io.tf instead of requesting a random new public IP, useful for DNS setup and changes
  # TODO: automate syncing
  azurePip:
    name: ldap-jenkins-io-ipv4
    resourceGroup: prod-public-ips
  lbAllowSources:
    # Tracked by updatecli - updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
    publick8s-out-lb: '20.85.71.108/32,20.22.30.9/32,20.22.30.74/32'
    # TODO: track with updatecli - https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
    publick8s-nat: '20.7.192.189/32'
    # Tracked by updatecli - updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
    publick8s-pods: '10.100.0.0/16'
    # Tracked by updatecli - updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
    puppet.jenkins.io: '20.12.27.65/32'
    # TODO: track with updatecli - https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
    trusted.ci.jenkins.io: '104.209.128.236/32'
    # TODO: track with updatecli - https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
    private.vpn.jenkins.io: '172.176.126.194/32'
    # TODO: track with updatecli - https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
    cert.ci.jenkins.io: '104.209.153.13/32'
    # Provided by LF
    linuxfoundation-staging: '34.211.101.61/32'
    # Provided by LF
    linuxfoundation-prod: '44.240.22.235/32'
    # Tracked by updatecli - updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
    privatek8s-out-lb: '20.22.6.81/32'
    # TODO: track with updatecli - https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
    privatek8s-nat: '20.65.63.127/32'
    # Tracked by updatecli - updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
    jfrog-artifactory: 34.233.58.83/32,34.201.191.93/32,18.214.241.149/32,54.236.124.56/32,34.199.85.0/32,54.204.174.26/32,54.237.44.112/32,52.1.113.0/32,52.86.38.82/32,44.198.238.218/32
    # Tracked by updatecli - updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
    azure.ci.jenkins.io: 68.154.31.56/32,20.57.126.88/32

resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector:
  kubernetes.io/arch: amd64

tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"

persistence:
  # Tracked by updatecli - updatecli/updatecli.d/configs/pvc-ldap.yaml
  customDataClaimName: ldap-jenkins-io-data
  # Tracked by updatecli - updatecli/updatecli.d/configs/pvc-ldap.yaml
  customBackupClaimName: ldap-jenkins-io-backup
