# Common values for all nginx-proxies
resources:
  limits:
    cpu: 2
    memory: 256Mi
  requests:
    cpu: 2
    memory: 256Mi

persistence:
  size: 50

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

podSecurityContext:
  fsGroup: 1000
