controller:
  replicaCount: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/instance"
                operator: In
                values:
                  - public-nginx-ingress
          topologyKey: "kubernetes.io/hostname"
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: false
      # azurerm_public_ip.publick8s_ipv4.ip_address in https://github.com/jenkins-infra/azure/blob/main/publick8s.tf
      service.beta.kubernetes.io/azure-load-balancer-ipv4: 20.7.178.24
      # azurerm_public_ip.publick8s_ipv6.ip_address in https://github.com/jenkins-infra/azure/blob/main/publick8s.tf
      service.beta.kubernetes.io/azure-load-balancer-ipv6: 2603:1030:408:5::15a
    externalTrafficPolicy: Local
    ipFamilies:
      - IPv4
      - IPv6
    ipFamilyPolicy: PreferDualStack
  nodeSelector:
    agentpool: x86medium
defaultBackend:
  nodeSelector:
    agentpool: x86medium
