controller:
  # TODO: remove when 1.14.3 is released
  image:
    tag: "v1.14.3"
    digest: sha256:82917be97c0939f6ada1717bb39aa7e66c229d6cfb10dcfc8f1bd42f9efe0f81
    digestChroot: sha256:ffdab64d0e0556f810d82d618a0fa97c4fc8dc2bc5717c51bfe83b5d4252c73e
  config:
    ## Ingress controller level
    # Only allow GitHub's webhooks requests - https://api.github.com/meta ("hooks", tracked by updatecli)
    whitelist-source-range: 140.82.112.0/20,143.55.64.0/20,185.199.108.0/22,192.30.252.0/22
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: false
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      service.beta.kubernetes.io/azure-pip-name: public-privatek8s
      # TODO: track with updatecli from https://reports.jenkins.io/jenkins-infra-data-reports/azure.json
      service.beta.kubernetes.io/azure-load-balancer-resource-group: prod-public-ips
    externalTrafficPolicy: Local
    ## Public LB level
    # Only allow GitHub's webhooks requests - https://api.github.com/meta ("hooks", tracked by updatecli)
    loadBalancerSourceRanges: ["140.82.112.0/20", "143.55.64.0/20", "185.199.108.0/22", "192.30.252.0/22"]
