---
ingress:
  enabled: true
  className: public-nginx
  annotations:
    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
    "nginx.ingress.kubernetes.io/ssl-redirect": "true"
  hosts:
    - host: alpha.docs.jenkins.io
      paths:
        - path: /
          serviceName: alpha-docs-jenkins-io
    - host: docs.origin.jenkins.io
      paths:
        - path: /
          serviceName: docs-jenkins-io
  tls:
    - secretName: alpha-docs-jenkins-io-tls
      hosts:
        - alpha.docs.jenkins.io
    # docs.jenkins.io certificate is managed by Fastly
    - secretName: docs-jenkins-io-tls
      hosts:
        - docs.origin.jenkins.io

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
htmlVolume:
  persistentVolumeClaim:
    claimName: alpha-docs-jenkins-io

replicaCount: 2

nodeSelector:
  kubernetes.io/arch: arm64

tolerations:
  - key: "kubernetes.io/arch"
    operator: "Equal"
    value: "arm64"
    effect: "NoSchedule"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app.kubernetes.io/name"
              operator: In
              values:
                - alpha-docs-jenkins-io
        topologyKey: "kubernetes.io/hostname"

podAnnotations:
  ad.datadoghq.com/nginx-website.logs: |
    [
      {"source":"nginx","service":"alpha.docs.jenkins.io"}
    ]
