jenkins:
    master:
        JCasC:
            enabled: true
            configScripts:
                jobs-settings: |
                    jobs:
                        - script: >
                            multibranchPipelineJob('release-jenkins-core') {
                              displayName "Release"
                              description "Jenkins Core Releases"
                              branchSources {
                                github {
                                  scanCredentialsId('github')
                                  repoOwner('olblak')
                                  repository('jenkins')
                                  includes('master')
                                }
                              }
                              factory {
                                workflowBranchProjectFactory {
                                  scriptPath('Jenkinsfile.release')
                                }
                              }
                            }
                        - script: >
                            multibranchPipelineJob('k8smgmt') {
                              displayName "Cluster Management"
                              description "Kubernetes Cluster Management"
                              branchSources {
                                github {
                                  scanCredentialsId('github')
                                  repoOwner('olblak')
                                  repository('charts')
                                  includes('master')
                                }
                              }
                            }

                ldap-settings: |
                    jenkins:
                      securityRealm:
                        ldap:
                          configurations:
                              - server: "${LDAP_SERVER}"
                                rootDN: "${LDAP_ROOT_DN}"
                                managerDN: "${LDAP_MANAGER_DN}"
                                managerPasswordSecret: "${LDAP_MANAGER_PASSWORD}"
                                userSearch: cn={0}
                          cache:
                              size: 100
                              ttl: 300

                matrix-settings: |
                    jenkins:
                      authorizationStrategy:
                        globalMatrix:
                          grantedPermissions:
                            - "Overall/Administer:release-core"
                            - "Overall/Read:release-core-dev"
                            - "Job/Build:release-core-dev"
                            - "Run/Replay:release-core-dev"
        ingress:
            enabled: true
            hostName: release.ci.jenkins.io
            annotations:
              "certmanager.k8s.io/acme-challenge-type": "dns01"
              "certmanager.k8s.io/acme-dns01-provider": "azure"
              "certmanager.k8s.io/cluster-issuer": "letsencrypt-prod"
              "kubernetes.io/ingress.class": "nginx"
              "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
            tls:
              - hosts:
                  - release.ci.jenkins.io
                secretName: release.ci.jenkins.io-cert
