jenkins:
    master:
        JCasC:
            enabled: true
            configScripts:
              k8s-settings: |
                jenkins:
                  clouds:
                    - kubernetes:
                        containerCapStr: "100"
                        jenkinsTunnel: "default-release-jenkins-agent:50000"
                        jenkinsUrl: "http://default-release-jenkins:8080"
                        maxRequestsPerHostStr: "32"
                        name: "kubernetes"
                        namespace: "release"
                        podRetention: "onFailure"
                        serverUrl: "https://kubernetes.default"
                        templates:
                          - name: jnlp-linux
                            nodeSelector: "kubernetes.io/os=linux"
                            containers:
                              - name: jnlp
                                image: "jenkins/jnlp-slave:3.29-1"
                                resourceLimitCpu: "400m"
                                resourceLimitMemory: "512Mi"
                                resourceRequestCpu: "400m"
                                resourceRequestMemory: "512Mi"
                          - name: jnlp-windows
                            nodeSelector: "kubernetes.io/os=windows"
                            containers:
                              - name: jnlp
                                args: "^${computer.jnlpmac} ^${computer.name}"
                                image: "jenkins4eval/jnlp-agent:latest-windows"
                                resourceLimitCpu: "400m"
                                resourceLimitMemory: "512Mi"
                                resourceRequestCpu: "400m"
                                resourceRequestMemory: "512Mi"
                            label: "jnlp-windows"
                            yaml: |-
                              spec:
                                tolerations:
                                - key: "os"
                                  operator: "Equal"
                                  value: "windows"
                                  effect: "NoSchedule"
                          - name: jenkins-release-linux
                            inheritFrom: "jnlp-linux"
                            label: "jenkins-release-linux "
                            nodeSelector: "kubernetes.io/os=linux"
                            nodeUsageMode: NORMAL
                            yamlMergeStrategy: "override"
                            containers:
                              - name: maven
                                command: "sleep"
                                args: "99d"
                                envVars:
                                  - containerEnvVar:
                                      key: "HOME"
                                      value: "/home/jenkins"
                                  - containerEnvVar:
                                      key: "MAVEN_OPTS"
                                      value: "-Xmx4g -Xms4g"
                                image: "olblak/maven:3-jdk-8"
                                resourceLimitCpu: "1"
                                resourceLimitMemory: "4Gi"
                                resourceRequestCpu: "1"
                                resourceRequestMemory: "4Gi"
                                ttyEnabled: true
                                workingDir: "/home/jenkins/agent"
                              - name: azure-cli
                                image: microsoft/azure-cli:2.0.59
                                alwaysPullImage: true
                                workingDir: "/home/jenkins/agent"
                                command: "sleep"
                                args: "99d"
                                ttyEnabled: true
                          - name: maven-windows
                            inheritFrom: "jnlp-windows"
                            label: "jenkins-release-windows"
                            yamlMergeStrategy: "override"
                            containers:
                              - name: maven
                                image: "jenkins4eval/maven-windows-jdk-8:latest"
                                command: "sleep"
                                args: "99d"
                                alwaysPullImage: true
                                resourceLimitCpu: "1"
                                resourceLimitMemory: "512Mi"
                                resourceRequestCpu: "0.5"
                                resourceRequestMemory: "512Mi"
                          - name: "helmfile"
                            inheritFrom: "jnlp-linux"
                            containers:
                              - name: "helmfile"
                                command: "sleep"
                                args: "99d"
                                envVars:
                                  - containerEnvVar:
                                      key: "HOME"
                                      value: "/home/jenkins"
                                image: "olblak/helmfile:b18357"
                                resourceLimitCpu: "400m"
                                resourceLimitMemory: "512Mi"
                                resourceRequestCpu: "400m"
                                resourceRequestMemory: "512Mi"
                                ttyEnabled: true
                                workingDir: "/home/jenkins/agent"
                            serviceAccount: "cluster-admin"
                            label: "helmfile"
                            podRetention: "onFailure"
                            yamlMergeStrategy: "override"
                          - name: "azure-cli"
                            inheritFrom: "jnlp-linux"
                            containers:
                              - name: "azure-cli"
                                command: "sleep"
                                args: "99d"
                                envVars:
                                  - containerEnvVar:
                                      key: "HOME"
                                      value: "/home/jenkins"
                                image: "microsoft/azure-cli:2.0.59"
                                resourceLimitCpu: "400m"
                                resourceLimitMemory: "512Mi"
                                resourceRequestCpu: "400m"
                                resourceRequestMemory: "512Mi"
                                ttyEnabled: true
                                workingDir: "/home/jenkins/agent"
                            label: "azure-cli"
                            podRetention: "onFailure"
                            yamlMergeStrategy: "override"
                          - name: "packaging"
                            inheritFrom: "jnlp-linux"
                            containers:
                              - name: "packaging"
                                command: "sleep"
                                args: "99d"
                                envVars:
                                  - containerEnvVar:
                                      key: "HOME"
                                      value: "/home/jenkins"
                                image: "olblak/packaging:0543e8"
                                resourceLimitCpu: "400m"
                                resourceLimitMemory: "512Mi"
                                resourceRequestCpu: "400m"
                                resourceRequestMemory: "512Mi"
                                ttyEnabled: true
                                workingDir: "/home/jenkins/agent"
                            label: "packaging"
                            podRetention: "onFailure"
                            yamlMergeStrategy: "override"
              jobs-settings: |
                jobs:
                  - script: >
                      multibranchPipelineJob('release-jenkins-core') {
                        displayName "Release"
                        description "Jenkins Core Releases"
                        branchSources {
                          github {
                            id('2019081601')
                            scanCredentialsId('github')
                            repoOwner('olblak')
                            repository('jenkins')
                            includes('master')
                          }
                        }
                        factory {
                          workflowBranchProjectFactory {
                            scriptPath('Jenkinsfile.release')
                          }
                        }
                      }
                  - script: >
                      multibranchPipelineJob('core-packaging') {
                        displayName "Packaging"
                        description "Jenkins Core Packaging"
                        branchSources {
                          github {
                            id('2019082101')
                            scanCredentialsId('github')
                            repoOwner('olblak')
                            repository('packaging')
                            includes('master')
                          }
                        }
                        factory {
                          workflowBranchProjectFactory {
                            scriptPath('Jenkinsfile')
                          }
                        }
                      }
                  - script: >
                      multibranchPipelineJob('k8smgmt') {
                        displayName "K8s Cluster Management"
                        description "Current K8s Cluster Management"
                        branchSources {
                          github {
                            id('2019081602')
                            scanCredentialsId('github')
                            repoOwner('jenkins-infra')
                            repository('charts')
                            includes('master')
                          }
                        }
                      }
              ldap-settings: |
                jenkins:
                  securityRealm:
                    ldap:
                      configurations:
                        - server: "${LDAP_SERVER}"
                          rootDN: "${LDAP_ROOT_DN}"
                          managerDN: "${LDAP_MANAGER_DN}"
                          managerPasswordSecret: "${LDAP_MANAGER_PASSWORD}"
                          userSearch: cn={0}
                      cache:
                        size: 100
                        ttl: 300
              matrix-settings: |
                jenkins:
                  authorizationStrategy:
                    globalMatrix:
                      grantedPermissions:
                        - "Overall/Administer:release-core"
                        - "Overall/Read:release-core-dev"
                        - "Job/Build:release-core-dev"
                        - "Job/Cancel:release-core-dev"
                        - "Job/Read:release-core-dev"
        ingress:
          enabled: true
          hostName: release.ci.jenkins.io
          annotations:
            "certmanager.k8s.io/cluster-issuer": "letsencrypt-prod"
            "kubernetes.io/ingress.class": "nginx"
            "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
          tls:
            - hosts:
                - release.ci.jenkins.io
              secretName: release.ci.jenkins.io-cert
