apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mirrorbits.fullname" . }}
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.mirrorbits }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mirrorbits.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mirrorbits.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum | trunc 63 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "mirrorbits.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.mirrorbits.repository }}:{{ .Values.image.mirrorbits.tag }}"
          imagePullPolicy: {{ .Values.image.mirrorbits.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /etc/mirrorbits
            {{ if $.Values.repository.persistentVolumeClaim.enabled -}}
            - name: binary
              mountPath: /srv/repo
            {{- end }}
            - name: geoipdata
              mountPath: /usr/share/GeoIP
          livenessProbe:
            httpGet:
              path: /?mirrorstats
              port: 8080
          readinessProbe:
            httpGet:
              path: /?mirrorstats
              port: 8080
          resources:
            {{- toYaml .Values.resources.mirrorbits | nindent 12 }}
        - name: crond
          image: "{{ .Values.image.mirrorbits.repository }}:{{ .Values.image.mirrorbits.tag }}-cron"
          imagePullPolicy: {{ .Values.image.mirrorbits.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            {{- toYaml .Values.resources.mirrorbits | nindent 12 }}
          volumeMounts:
            {{ if $.Values.repository.persistentVolumeClaim.enabled -}}
            - name: binary
              mountPath: /srv/repo
            {{- end }}
        - name: geoipupdate
          image: "{{ .Values.geoipupdate.image.repository }}:{{ .Values.geoipupdate.image.tag }}"
          imagePullPolicy: {{ .Values.image.mirrorbits.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: geoipdata
              mountPath: /usr/share/GeoIP
          resources:
            {{- toYaml .Values.resources.mirrorbits | nindent 12 }}
          env:
            - name: GEOIPUPDATE_EDITION_IDS
              value: {{ .Values.geoipupdate.editions }}
            - name: GEOIPUPDATE_FREQUENCY
              value: {{ .Values.geoipupdate.update_frequency | quote }}
          envFrom:
          - secretRef:
              name: {{ include "mirrorbits.fullname" . }}-geoipupdate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: conf
          secret:
            secretName: {{ include "mirrorbits.fullname" . }}
            items: 
              - key: mirrorbits.conf
                path: mirrorbits.conf
        - name: geoipdata
          emptyDir: {}
        {{ if $.Values.repository.persistentVolumeClaim.enabled -}}
        - name: binary
          persistentVolumeClaim:
            claimName: {{ include "mirrorbits.fullname" . }}-binary
        {{- end -}}
