---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}
type: Opaque
data:
  mirrorbits.conf: {{ .Values.mirrorbits.conf | b64enc }}

{{ if $.Values.repository.secrets.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}-binary
type: Opaque
data:
  {{- range $key, $val := .Values.repository.secrets.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirrorbits.fullname" . }}-geoipupdate
type: Opaque
data:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.geoipupdate.account_id | b64enc }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.geoipupdate.license_key | b64enc }}
