# Default values for mirror.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
strategy:
  #rollingUpdate:
  #  maxSurge: 25%
  #  maxUnavailable: 25%
  #type: RollingUpdate
  # By default we use an azure disk which do not support multi mount so
  # we must be sure that all containers are stopped before deploying the new one
  type: Recreate
images:
  web:
    repository: httpd
    tag: 2.4
    pullPolicy: Always
  cron:
    repository: olblak/crond
    tag: latest
    pullPolicy: Always
  rsyncd:
    repository: jenkinsciinfra/rsyncd@sha256
    tag: d129d0d5a075255a0ede3e9e3ef4a0a28809ec6ae5a56cb3ae19a0636a5d0397
    pullPolicy: Always
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  web:
    type: ClusterIP
    port: 80
    #    IP:
    #    whitelisted_sources:
    #      - 
  rsyncd:
    type: ClusterIP
    port: 873
    #    IP:
    whitelisted_sources:
      - 52.167.253.43/32
      - 52.202.51.185/32
#ingress:
#  enabled: true
#  annotations: 
#    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
#    "kubernetes.io/ingress.class": "nginx"
#    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
#
#  hosts:
#    - host: mirror.jenkins.io
#
#  tls:
#    - secretName: releasemirror-tls
#      hosts:
#        - mirror.jenkins.io
resources:
  web:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  cron:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  rsyncd:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
nodeSelector: {}
tolerations: []
affinity: {}
persistent:
  volume:
    name: mirror-binary
    enabled: false
    spec: {}
  volumeClaim:
    name: mirror-binary
    enabled: false
    spec:
      storageClassName: default
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
  secret:
    name: mirror-binary
    enabled: false
    data: {}
synchronize:
  enabled: false
  upstream: "rsync://ftp-osl.osuosl.org/jenkins/"
  period: "*/5 * * * *"
