# Default values for mirror.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  web:
    repository: nginx
    tag: 1.17
    pullPolicy: Always
  cron:
    repository: olblak/crond
    tag: latest
    pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

#ingress:
#  enabled: true
#  annotations: 
#    "cert-manager.io/cluster-issuer": "letsencrypt-prod"
#    "kubernetes.io/ingress.class": "nginx"
#    "nginx.ingress.kubernetes.io/proxy-body-size": "500m"
#
#  hosts:
#    - host: mirror.jenkins.io
#
#  tls:
#    - secretName: releasemirror-tls
#      hosts:
#        - mirror.jenkins.io

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistent:
  volume:
    name: mirror-binary
    enabled: false
    spec: {}
  volumeClaim:
    name: mirror-binary
    enabled: false
    spec:
      storageClassName: default
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 200Gi
  secret:
    name: mirror-binary
    enabled: false
    spec: {}

synchronize:
  enabled: false
  upstream: "rsync://ftp-osl.osuosl.org/jenkins/"
  period: "*/5 * * * *"

