releases:
  - name: public-nginx-ingress
    chart: ingress-nginx/ingress-nginx
    namespace: public-nginx-ingress
    version: 4.0.5
    wait: true
    timeout: 300
    atomic: true
    values:
      - defaultBackend:
          enabled: true
          image:
            repository: jenkinsciinfra/404
            tag: 0.2.1
          ## Unprivileged port as non root user and no escalation allowed
          port: 8080
          ## Volumes are required because rootfs is readonly
          extraVolumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-rundir
              mountPath: /var/run/nginx
            - name: nginx-logs
              mountPath: /var/logs/nginx
          extraVolumes:
            - name: nginx-cache
              emptyDir: {}
            - name: nginx-rundir
              emptyDir: {}
            - name: nginx-logs
              emptyDir: {}
      - controller:
          config:
            log-format-upstream: '[$proxy_add_x_forwarded_for] - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
            # In order to use geoIP from the ingress controller,
            # we need to provide a maxmind license key.
            # I doubt we need it at the moment, hence this comment.
            # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-geoip2
            use-geoip2: "true"
            hsts: "true"
            hsts-preload: "true"
            hsts-include-subdomains: "true"
            # Should be 2 years as per https://hstspreload.org/
            hsts-max-age: "86400" # 24 hours, as a first gradual HSTS deployment - see INFRA-2998
          replicaCount: 2
          ingressClass: public-ingress
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: false
              service.beta.kubernetes.io/azure-load-balancer-internal-subnet: app-tier
              service.beta.kubernetes.io/azure-load-balancer-resource-group: prodpublick8s
              prometheus.io/scrape: "true"
              prometheus.io/port: "10254"
            loadBalancerIP: 52.167.253.43
            externalTrafficPolicy: Local
  - name: private-nginx-ingress
    chart: ingress-nginx/ingress-nginx
    namespace: private-nginx-ingress
    version: 4.0.5
    wait: true
    timeout: 300
    atomic: true
    values:
      - defaultBackend:
          enabled: true
          image:
            repository: jenkinsciinfra/404
            tag: 0.2.1
          ## Unprivileged port as non root user and no escalation allowed
          port: 8080
          ## Volumes are required because rootfs is readonly
          extraVolumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-rundir
              mountPath: /var/run/nginx
            - name: nginx-logs
              mountPath: /var/logs/nginx
          extraVolumes:
            - name: nginx-cache
              emptyDir: {}
            - name: nginx-rundir
              emptyDir: {}
            - name: nginx-logs
              emptyDir: {}
      - controller:
          config:
            log-format-upstream: '[$proxy_add_x_forwarded_for] - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
            # In order to use geoIP from the ingress controller,
            # we need to provide a maxmind license key.
            # I doubt we need it at the moment, hence this comment.
            # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-geoip2
            use-geoip2: "true"
          replicaCount: 2
          ingressClass: nginx
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: true
              service.beta.kubernetes.io/azure-load-balancer-internal-subnet: data-tier
              prometheus.io/scrape: "true"
              prometheus.io/port: "10254"
            externalTrafficPolicy: Local
