releases:
    - name: public-nginx-ingress
      chart: stable/nginx-ingress
      namespace: kube-system
      version: 1.4.0
      wait: true
      timeout: 600
      recreatePods: true
      force: true
      atomic: true
      values:
        - defaultBackend:
            enabled: true
            image:
              repository: jenkinsciinfra/404
              tag: 5-build19b813
            port: 80
            replicaCount: 3
        - controller:
            ingressClass: public-ingress
            service:
                annotations:
                  service.beta.kubernetes.io/azure-load-balancer-internal: false
                  service.beta.kubernetes.io/azure-load-balancer-internal-subnet: app-tier
                  service.beta.kubernetes.io/azure-load-balancer-resource-group: prodpublick8s
                loadBalancerIP: 52.147.174.4

    - name: private-nginx-ingress
      chart: stable/nginx-ingress
      namespace: kube-system
      version: 1.4.0
      wait: true
      timeout: 600
      recreatePods: true
      force: true
      atomic: true
      values:
        - defaultBackend:
            enabled: true
            image:
              repository: jenkinsciinfra/404
              tag: 5-build19b813
            port: 80
            replicaCount: 3
        - controller:
            ingressClass: nginx
            service:
                annotations:
                  service.beta.kubernetes.io/azure-load-balancer-internal: true
                  service.beta.kubernetes.io/azure-load-balancer-internal-subnet: data-tier
