releases:
  - name: public-nginx-ingress
    chart: ingress-nginx/ingress-nginx
    namespace: public-nginx-ingress
    version: 4.0.6
    wait: true
    timeout: 300
    atomic: true
    values:
      - "../config/publick8s/public-nginx-ingress.yaml"
  - name: private-nginx-ingress
    chart: ingress-nginx/ingress-nginx
    namespace: private-nginx-ingress
    version: 4.0.6
    wait: true
    timeout: 300
    atomic: true
    values:
      - "../config/publick8s/private-nginx-ingress.yaml"
