repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
releases:
    - name: prometheus
      namespace: prometheus
      chart: stable/prometheus
      wait: true
      timeout: 600
      force: true
      atomic: true
      values:
        - "../config/default/prometheus.yaml"
