repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: prometheus
    namespace: prometheus
    chart: prometheus-community/prometheus
    wait: true
    timeout: 300
    version: 14.10.0
    force: false
    atomic: false
    values:
      - "../config/default/prometheus.yaml"
