repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
releases:
- name: prometheus
  namespace: prometheus
  chart: stable/prometheus
  wait: true
  timeout: 600
  version: 11.10.0
  force: false
  atomic: true
  values:
  - "../config/default/prometheus.yaml"
