apiVersion: v1
kind: Service
metadata:
  name: {{ include "uplink.fullname" . }}
  labels:
{{ include "uplink.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3030
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "uplink.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
